### ISSUE TITLE
Server Crash with Simplypaths

### ISSUE THREAD

**Issue by FrostySigh** [Zundrel/Simply-Paths#1]
So, yeah whenever I add simplypaths 1.0.5C so my Forge server it crashes when I start it, and this here: http://pastebin.com/Y28zX9eS is the crash-log (It might be some other mod it is conflicting with since I have over 250 mods in this pack)

**Comment by Wargog** [comment]
Could you post it on GitHub with the little ` symbols? That's the symbol under the ~ on a standard QWERTY keyboard.

**Comment by FrostySigh** [comment]
huh?

**Comment by Wargog** [comment]
Post the error report surronded by the little ` symbols. I am going to take a look at the error report but I can't access pastebin right now. Putting those little symbols around it will put it in code format `like this.`

**Comment by FrostySigh** [comment]
Ah, So like this? 
` ---- Minecraft Crash Report ----
// Ooh. Shiny.

Time: 2/9/15 2:19 PM
Description: Exception in server tick loop

cpw.mods.fml.common.LoaderException: java.lang.NoSuchFieldError: nameTexture
        at cpw.mods.fml.common.LoadController.transition(LoadController.java:162)
        at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:515)
        at cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:88)
        at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:314)
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:117)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
Caused by: java.lang.NoSuchFieldError: nameTexture
        at com.momnop.simplypaths.blocks.BlockRotatingPath.<init>(BlockRotatingPath.java:46)
        at com.momnop.simplypaths.blocks.SimplyPathsBlocks.load(SimplyPathsBlocks.java:30)
        at com.momnop.simplypaths.SimplyPaths.preInit(SimplyPaths.java:38)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513)
        at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
        at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
        at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
        at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
        at com.google.common.eventbus.EventBus.post(EventBus.java:275)
        at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
        at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
        at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
        at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
        at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
        at com.google.common.eventbus.EventBus.post(EventBus.java:275)
        at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
        at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:513)
        ... 5 more `

That doesn't work for me

**Comment by Wargog** [comment]
It's only the server crashing? Where did you download from, CI or Curse?

**Comment by FrostySigh** [comment]
Curse

**Comment by Wargog** [comment]
Ok, I don't see any errors in the file in the crash report. I could be due to the server trying to render when it doesn't have the ability to do so. We'll take a better look when we have the chance.

**Comment by FrostySigh** [comment]
Okay, sounds good :)

**Comment by Wargog** [comment]
Ok, the Rotating Path block is being placed somewhere on your server, which is executing an event that is crashing the server. That is as far as I can see into that error log. Try running the server with just SimplyPaths loaded and place one of the Rotating Path blocks down. If that doesn't work try to use the latest version from the CI which you can find on the badge on the main badge in the README.md

**Comment by FrostySigh** [comment]
Nope, that doesn't work, even if I remove the world from the server; http://pastebin.com/BPXWqB1c
Is there any mod that SimplyPaths is depending on, like CoFH core or some other core mod?

**Comment by Wargog** [comment]
There aren't any other mods that it depends on, I will have Zundrel take a look when he gets the time.

**Comment by Shrimpstress** [comment]
Ok so. I'd prefer you leave the support to me Wargog. You haven't even used the mod before, I've only told you of it.

Anyway. I know what the issue is and it'll be fixed and a build released pronto.. It's just a small oversight on my part. Sorry about the crash!

This'll also give me a chance to release a few of my bug fixes and things.

**Comment by Shrimpstress** [comment]
Commit c08a9bb fixes this.

**Comment by FrostySigh** [comment]
That sounds very nice :) If it keeps crashing I'll let you know after the update that is :P

**Comment by Shrimpstress** [comment]
1.0.5d should be out anytime now. Go get it. Should fix the issue and a few other small things.

**Comment by Shrimpstress** [comment]
Scrap that. Made a large derp. It fixed the issue, right, but it also messed up textures.

**Comment by Shrimpstress** [comment]
Ok now it's actually out. Have fun.

**Comment by FrostySigh** [comment]
It starts now, thank you :)

**Comment by Shrimpstress** [comment]
No problem. Glad to help!
